#!/usr/bin/env Rscript
library(MLmetrics)
smp_size <- floor(0.75 * nrow(z))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(z)), size = smp_size)

train <- z[train_ind, ]
test <- z[-train_ind, ]

a <- glm(delta_time ~., train, family = poisson(link = "log"))
summary(a)

x_test <- test[-c(6)]
y_test <- test[c(6)]

y_pred <- predict(a, x_test, type="response")

rsq <- function (x, y) cor(x, y) ^ 2
rsq(y_pred, y_test)

y_test = as.vector(t(y_test))
MAPE(y_pred, y_test)
